[
"uci set system.@system[0].hostname='DUT_Banana'",
"uci set system.ntp.server='0.ntp2.stratum2.ru'",
"uci set system.@system[0].zonename='Europe/Minsk'",
"uci set system.@system[0].timezone='<+03>-3'",
"uci set firewall.@zone[1].forward='ACCEPT'",
"uci set firewall.@zone[1].input='ACCEPT'",
"uci set firewall.@defaults[0].input='ACCEPT'",
"uci set firewall.@defaults[0].output='ACCEPT'",
"uci set firewall.@defaults[0].flow_offloading='1'",
"uci set firewall.@defaults[0].flow_offloading_hw='1'",
"uci set firewall.@defaults[0].synflood_protect='1'",
"uci set firewall.@defaults[0].forward='ACCEPT'",
"uci set firewall.@defaults[0].flow_offloading='1'",
"uci set firewall.@defaults[0].flow_offloading_hw='1'",
"uci set network.gre=interface",
"uci set network.gre.proto='gre'",
"uci set network.gre.force_link='1'",
"uci set network.gre.peeraddr='200.1.1.2'",
"uci set network.gre.ipaddr='192.168.1.1'",
"uci set network.gre.delegate='0'",
"uci add firewall zone # =cfg0edc81",
"uci set firewall.@zone[-1].name='gre'",
"uci set firewall.@zone[-1].input='ACCEPT'",
"uci set firewall.@zone[-1].output='ACCEPT'",
"uci set firewall.@zone[-1].forward='ACCEPT'",
"uci add_list firewall.@zone[-1].network='gre'",
"uci add firewall forwarding # =cfg0fad58",
"uci set firewall.@forwarding[-1].src='gre'",
"uci set firewall.@forwarding[-1].dest='lan'",
"uci add firewall forwarding # =cfg10ad58",
"uci set firewall.@forwarding[-1].src='lan'",
"uci set firewall.@forwarding[-1].dest='gre'",
"uci set network.wan.proto='static'",
"uci set network.wan.ipaddr='200.1.1.1'",
"uci set network.wan.netmask='255.255.255.0'",
"uci set network.wan.delegate='0'",
"uci add network route # =cfg08c8b4",
"uci set network.@route[-1].interface='gre'",
"uci set network.@route[-1].target='192.168.2.0/24'",
"uci commit",
"mwan3 stop",
"uci commit",
" /etc/init.d/network reload"
]

